src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java

This fixes a defect that was introduced in bd98b91ea614c307a6bb1e0af36d9dd2a5646e29 whereby upgrading the plugin would have forced users to re-enter the TFS account's password in each job.  Upgrades to the plugin will now be safe and without loss of data.
Manual testing
--------------
1. Create job that polls TFS using version 3.1.1 of the plugin.  Verify it can authenticate to the TFS server.  Notice the job's `config.xml` file contains a `userPassword` element.
2. Upgrade the plugin to include the changes from this branch. (this may require restarting Jenkins)
3. Verify the job created in step 1 can still authenticate to the TFS server.
4. Edit the job's configuration and hit Save without changing anything.  Notice the job's `config.xml` file no longer contains a `userPassword` element …

Fix upgrade to Secret

---

src/main/java/hudson/plugins/tfs/TFSLabeler.java

The overridden newInstance() method was causing the whenToLabel
element to be removed from a job's config.xml file when a configuration update was made.
This required the user to manually edit the job's config.xml file and reload configuration from disk.

[FIXED JENKINS-23344] - Fixed whenToLabel in config.xml

---

src/main/java/hudson/plugins/tfs/model/Server.java

This fixes a defect whereby the first instance of Server would think
default NT credentials are not supported and fail miserably unless
credentials were provided.  Subsequent instances would be fine.

Need native libraries to check for default creds.

---

src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
src/main/java/hudson/plugins/tfs/actions/CheckoutAction.java
src/main/java/hudson/plugins/tfs/commands/AbstractCommand.java
src/main/java/hudson/plugins/tfs/commands/RemoteChangesetVersionCommand.java
src/main/java/hudson/plugins/tfs/model/Project.java
src/main/java/hudson/plugins/tfs/util/DateUtil.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java
src/test/java/hudson/plugins/tfs/actions/CheckoutActionTest.java
src/test/java/hudson/plugins/tfs/commands/RemoteChangesetVersionCommandTest.java
src/test/java/hudson/plugins/tfs/util/DateUtilTest.java

Two defects were discovered in the implementation of pull request #24:
1. The value of `VERSION_SPEC` was incorrectly applied.
2. The reported SCM changes between builds by version spec was incorrectly querying TFVC.
Outstanding weirdness/defect:
-------------------------------
I created a job with polling, then added the `VERSION_SPEC` parameter with a default value of `LFoo` (a label that pointed to changeset 4).  Running a build indeed got the source from changeset 4, but then subsequent polling would detect that a changeset newer than 4 existed and queue a build.  The build would again obtain changeset 4 and the loop repeated itself until I turned off polling or removed the default value.
Part of the problem was due to configuration error (it probably doesn't make sense to supply a …

Fix checkout by version spec

---

src/main/java/hudson/plugins/tfs/commands/AbstractCallableCommand.java
src/main/java/hudson/plugins/tfs/model/MockableVersionControlClient.java
src/main/java/hudson/plugins/tfs/model/Project.java
src/main/java/hudson/plugins/tfs/model/Server.java
src/test/java/hudson/plugins/tfs/EndToEndTfs.java
src/test/java/hudson/plugins/tfs/FunctionalTest.java
src/test/java/hudson/plugins/tfs/commands/AbstractCallableCommandTest.java
src/test/java/hudson/plugins/tfs/model/ServerIntegrationTest.java

In preparation of replacing the use of tf[.cmd|.exe] with the TFS SDK for Java, these abstractions will allow us to keep many of the existing tests, with minor modifications.
These changes were made while prototyping the transition for `DeleteWorkspaceCommand` and `NewWorkspaceCommand`.

Helpers to facilitate transition to Java TFS SDK

---

src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
src/main/java/hudson/plugins/tfs/actions/CheckoutAction.java
src/main/java/hudson/plugins/tfs/commands/RemoteChangesetVersionCommand.java
src/main/java/hudson/plugins/tfs/model/Project.java
src/test/java/hudson/plugins/tfs/FunctionalTest.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java
src/test/java/hudson/plugins/tfs/actions/CheckoutActionTest.java

Previously, checking out (and subsequent history querying) was done using timestamps, which could lead to an inconsistency where the plugin, under certain circumstances (i.e. if the build was started on the same second as a check-in) could report the changeset associated with the build as **x** but the files actually fetched would be from changeset **x - 1**.
This pull request leverages the changeset number (already being recorded!) to perform the checkout and history querying with more precision and consistency.
Verification is mostly encoded in the `newJob()` test, although some validation also took place by manual inspection of build artifacts, such as logs.

Checkout and history now go by the changeset number

---

src/main/java/hudson/plugins/tfs/commands/DeleteWorkspaceCommand.java
src/main/java/hudson/plugins/tfs/commands/NewWorkspaceCommand.java
src/test/java/hudson/plugins/tfs/EndToEndTfs.java
src/test/java/hudson/plugins/tfs/commands/DeleteWorkspaceCommandTest.java
src/test/java/hudson/plugins/tfs/commands/NewWorkspaceCommandTest.java

There are some corner cases where attempting to find a workspace by a user's userName will fail if it was created using the user's display name.  The SDK has a concept for "whoever is authenticated" (i.e. the `AUTHENTICATED_USER` constant), so let's use that.
Testing
-------
The integration tests were successful against TFS 2012, 2013 and 2015.  A quick peek at one of the build logs revealed that the new log messages indeed look better.  Mission accomplished!

Increase workspace resolution resiliency

---

src/main/java/hudson/plugins/tfs/commands/DeleteWorkspaceCommand.java
src/test/java/hudson/plugins/tfs/commands/DeleteWorkspaceCommandTest.java

This is a corner case that used to fail when attempting to delete a workspace owned by the previous user but queried using the current user's name.  Now we query for all workspaces with the name and attempt to delete them.  The new user must have the "Administer" permision on the previous user's workspace to be able to delete it, though.

Handle switching the user account.

---

src/main/java/hudson/plugins/tfs/commands/DeleteWorkspaceCommand.java

Sometimes, the `WorkspacesTest.assertWorkspaceIsDeletedFromMap()` test would execute before a test that would initialize the location of the native libraries.  This change moves the call to `LocalHost.getShortName()` such that the aforementioned test will not try to trigger that code path.
This effectively fixes the occasional test failures introduced by pull request #48.

Delay-load computerName to avoid failing tests.

---

src/main/java/hudson/plugins/tfs/commands/LabelCommand.java
src/test/java/hudson/plugins/tfs/AbstractIntegrationTest.java
src/test/java/hudson/plugins/tfs/EndToEndTfs.java
src/test/java/hudson/plugins/tfs/FunctionalTest.java
src/test/java/hudson/plugins/tfs/IntegrationTestHelper.java
src/test/java/hudson/plugins/tfs/IntegrationTestHelperTest.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmIntegrationTest.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java
src/test/java/hudson/plugins/tfs/commands/ListWorkspacesCommandTest.java
src/test/java/hudson/util/SecretOverride.java

These changes make it possible to set-up automated integration testing against _any_ VSO account, similar to how we can run those tests against on-premises TFS servers.

Add Visual Studio Online support, part 1.

---

src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
src/main/resources/hudson/plugins/tfs/TeamFoundationServerScm/global.jelly
src/main/webapp/tfExecutable.html
src/test/resources/hudson/plugins/tfs/FunctionalTest/agent/hudson.plugins.tfs.TeamFoundationServerScm.xml
src/test/resources/hudson/plugins/tfs/FunctionalTest/createLabel/hudson.plugins.tfs.TeamFoundationServerScm.xml
src/test/resources/hudson/plugins/tfs/FunctionalTest/newJob/hudson.plugins.tfs.TeamFoundationServerScm.xml

Now that the plugin no longer needs the TFS command-line-client (CLC), let's remove it from the configuration.

Clean up after TF CLC -> SDK switchover

---

src/main/java/hudson/plugins/tfs/model/Project.java
src/test/java/hudson/plugins/tfs/model/ProjectTest.java

Originally raised through #53, this pull request includes an integration test that reproduces the issue and a minimal fix to the `getDetailedHistory(String)` method overload.

More efficient single version history

---

src/test/java/hudson/plugins/tfs/FunctionalTest.java
src/test/resources/hudson/plugins/tfs/FunctionalTest/agent/jobs/agent/config.xml

With this change, that integration test now works on platforms other than Windows, provided the `COMPUTERNAME` environment variable is defined.

Fix agent test on other os

---

pom.xml
src/main/java/hudson/plugins/tfs/ChangeSetWriter.java
src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
src/main/java/hudson/plugins/tfs/browsers/TeamFoundationServerRepositoryBrowser.java
src/main/java/hudson/plugins/tfs/model/Project.java
src/main/java/hudson/plugins/tfs/model/UserLookup.java
src/main/java/hudson/plugins/tfs/model/Workspaces.java
src/main/java/hudson/plugins/tfs/util/BuildVariableResolver.java
src/main/java/hudson/plugins/tfs/util/TextTableParser.java

Previously Javadoc code documentation comments would only be verified during release; now it's done as part of the `verify` phase.
Fixed all warnings/errors reported by `mvn javadoc:jar`, which is a faster way to check what the Javadoc compiler has to say about the code. (it runs in less than 5 seconds)

Fix Javadoc errors and enforce Javadoc verification

---

pom.xml

The `jar` goal meant TWO copies of `tfs-javadoc.jar` would be uploaded to the `releases` repository upon release, whereas we don't even need the JAR built during `verify`, we just want to find any errors & warnings.
Manual testing
--------------
Temporarily re-introduced some JavaDoc errors in the code, then ran `mvn verify` to confirm the build would fail due to said errors.  Whether this fixes the release performance will be confirmed next release.

Improve JavaDoc verification

---

pom.xml
src/main/webapp/WEB-INF/lib/redist.txt
src/test/java/hudson/plugins/tfs/EndToEndTfs.java

CI builds started failing integration tests with:
```
java.lang.IllegalArgumentException: Owners must be the same: jenkins-tfs-plugin@outlook.com vs. Windows Live ID\jenkins-tfs-plugin@outlook.com
at com.microsoft.tfs.util.Check.throwForFalse(Check.java:173)
at com.microsoft.tfs.util.Check.isTrue(Check.java:115)
at com.microsoft.tfs.core.clients.versioncontrol.workspacecache.WorkspaceInfo.update(WorkspaceInfo.java:672)
at com.microsoft.tfs.core.clients.versioncontrol.workspacecache.internal.InternalCache.merge(InternalCache.java:865)
at com.microsoft.tfs.core.clients.versioncontrol.workspacecache.internal.InternalCache.save(InternalCache.java:646)
at com.microsoft.tfs.core.clients.versioncontrol.workspacecache.internal.InternalCacheLoader.saveConfigIfDirty(InternalCacheLoader.java:210)
at …
```

Fix VSTS workspace management

---

src/main/java/hudson/plugins/tfs/browsers/TeamSystemWebAccessBrowser.java
src/main/java/hudson/plugins/tfs/util/License.txt
src/main/java/hudson/plugins/tfs/util/QueryString.java
src/main/java/hudson/plugins/tfs/util/UriHelper.java
src/main/webapp/browsers/tswa.html
src/test/java/hudson/plugins/tfs/FunctionalTest.java
src/test/java/hudson/plugins/tfs/browsers/TeamSystemWebAccessBrowserTest.java

Team Foundation Server (TFS) drastically changed the URLs to changesets, file contents and file diffs in TFS 2012, breaking links from Jenkins.  In TFS 2013 and 2015, the links generated by the web UI are slightly different but TFS 2012-style links are compatible.
Replaces pull request #26.
The `TSWAHyperlinkBuilder` class, despite not having a method for generating a link to a file diff, was used for a prototype.
Although it worked, with an overhead of _at least_ one remote procedure call (RPC) _per hyperlink_, the performance was deemed unacceptable.
Commit 3619ef3742f18f89aba6f12b34bd8013286c185d was added to the `documentation_4.1.0` branch. 
Here's a screenshot of the results of updating `src/main/webapp/browsers/tswa.html`, seen in context and with sample values:
1. Upload private …

[JENKINS-16207] Repo browser links fixed

---

README.md
src/main/java/hudson/plugins/tfs/browsers/TeamSystemWebAccessBrowser.java

to be up to date with product names and in sync with git plugin
See https://github.com/jenkinsci/git-plugin/pull/387
Tested this on local run and test deployment.

Updated repo browser label 

---

src/main/java/hudson/plugins/tfs/model/ChangeSet.java

Slight improvement of #76.
Manual testing
--------------
1. Install the [Delivery Pipeline Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Delivery+Pipeline+Plugin).
2. Create a new job called **JENKINS-32394**
1. Check the **Delivery Pipeline configuration** box and configure as follows:
1. *Stage Name*: **Development**
2. *Task Name*: **Build**
3. *Customize Task Description Template*: **Build #${BUILD_NUMBER} on ${NODE_NAME}**
2. Select **Team Foundation Server** under *Source Code Management* and configure to get source code from a TFVC project.
3. Add a build step just to see the build doing something.  I used **Execute Windows batch command** set to `dir /s`
4. Click **[Save]**
3. Click **Build Now** on the new job.
4. Go to the Jenkins home and click the "+" on the top tab row …

JENKINS-32394: Fix Changeset number display for Delivery Pipeline

---

src/main/java/hudson/plugins/tfs/model/ChangeSet.java

Should fix bug when using slack and tfs within the same project

Implemented getAffectedFiles in ChangeSet

---

src/main/java/hudson/plugins/tfs/model/Project.java
src/test/java/hudson/plugins/tfs/model/ProjectTest.java

We noticed this issue last night. If you add a cloaked path like " $/Server/TeSt2" when the actual folder name on the server is "test2", a build will still be triggered if someone checks into that folder. The polling is case sensitive.
This is a quick fix for this case, polling is now insensitive.
No changes are needed to the get, it's already case insensitive. Polling now matches this behavior.

Cloaked paths should be case insensitive when polling for changes

---

src/main/java/hudson/plugins/tfs/commands/DeleteWorkspaceCommand.java
src/main/java/hudson/plugins/tfs/model/MockableVersionControlClient.java

It appears Visual Studio Team Services may have changed, in the last few months, the value of what the TFS SDK for Java maps to the `ownerName` attribute in the `Cache/VersionControl.config` file.  Previously, it appears the VSTS account e-mail address was stored (one of the `OwnerAlias` values) and now it's a GUID.  
Whatever the cause for this change, it means deleting a workspace that was created when `ownerName` wasn't a GUID will succeed in completing the operation on the server but the corresponding entry will not be removed from the cache (because it's looking for a workspace with an `ownerName` being a GUID), which will cause the subsequent workspace re-creation to succeed in completing the operation on the server, but fail when attempting to update the cache, saying there are two …

Work around TFS SDK defect when re-creating an older workspace

---

pom.xml
src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
src/test/java/hudson/plugins/tfs/FunctionalTest.java
src/test/java/hudson/plugins/tfs/IntegrationTestHelper.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java
src/test/java/hudson/plugins/tfs/browsers/TeamSystemWebAccessBrowserTest.java
src/test/java/hudson/util/SecretOverride.java
src/test/java/jenkins/security/ConfidentialStoreOverride.java

Most of the resulting modifications were test-related.
Manual testing
--------------
1. `mvn verify clean`
2. Install `target/tfs.hpi` in a Jenkins instance.
3. Click around to configure a job that uses the TFS plugin, hit Save and go back to make sure the values are still there.
4. Queue a build that pull sources from TFVC.
Initial smoke tests pass!  The one thing that no longer appears to work is running through `mvn hpi:run` and that appears to be a problem with the classpath.

Upgrade Jenkins dependencies to 1.580

---

pom.xml

A side effect of https://github.com/jenkinsci/tfs-plugin/pull/81 is that the language level for Jenkins plugin compilation (and Jenkins) changes to Java 6. 
This PR fixes the build check to validate java 6 instead of java 5. This essentially allows Java 6 usage without breaking the build (not that there were any language changes but anyway...) .
Ran full build and tested deployment and usage of plugin manually. No IT runs necessary since build output is not affected by this change.
This PR and the above merged PR replace https://github.com/jenkinsci/tfs-plugin/pull/62, which I will close.
Unless there are any objections I will merge this tomorrow. fyi @olivierdagenais

changed language level check to use 1.6

---

src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java

The updated core dependency to 1.580 allows us to override the new guessBrowser method. It sets a default web access browser if none is configured on a job.
Since there is only one TFVC web browser implementation we can assume it to be used and therefore activated when "(Auto)" e.g. nothing , is configured in the SCM sections "Repository browser"	drop down.
Full build is passing. 
Tested with a Jenkins 2.7.1 instance and a TFS server as well as a VS Online account. Works as expected.

Automatically configure used webbrowser access

---

pom.xml
src/main/java/hudson/plugins/tfs/VstsCollectionConfiguration.java
src/main/java/hudson/plugins/tfs/VstsPluginGlobalConfig.java
src/main/java/hudson/plugins/tfs/util/QueryString.java
src/main/java/hudson/plugins/tfs/util/StringHelper.java
src/main/java/hudson/plugins/tfs/util/UriHelper.java
src/main/resources/hudson/plugins/tfs/TeamFoundationServerScm/global.jelly
src/main/resources/hudson/plugins/tfs/VstsCollectionConfiguration/config.groovy
src/main/resources/hudson/plugins/tfs/VstsCollectionConfiguration/help-collectionUrl.html
src/main/resources/hudson/plugins/tfs/VstsPluginGlobalConfig/config.groovy
src/main/resources/hudson/plugins/tfs/VstsPluginGlobalConfig/help.jelly
src/test/java/hudson/plugins/tfs/VstsCollectionConfigurationTest.java
src/test/java/hudson/plugins/tfs/util/QueryStringTest.java
src/test/java/hudson/plugins/tfs/util/UriHelperTest.java

These changes add a new section to the global configuration, where one or more pairs of *Team Project Collection* URL and Credentials can be added (and tested!):
This also lays the groundwork for [JENKINS-13663: Allow use of credentials from Credentials Plugin](https://issues.jenkins-ci.org/browse/JENKINS-13663).
Manual testing
--------------
As can be seen in the screenshot, I added some credentials to Jenkins and then was able to select them when adding/editing team project collections.
The [Test connection] button mostly works for finding errors in the URL and appears to use NTLM when communicating with TFS (even when credentials are provided), so more testing would be required on that front, especially when the Jenkins master is not in a domain, running as a domain user or on Windows.

Add global configuration of Team Project Collections and associated credentials

---

src/main/java/hudson/plugins/tfs/model/GitCodePushedEventArgs.java
src/main/java/hudson/plugins/tfs/model/GitStatusContext.java
src/main/java/hudson/plugins/tfs/model/GitStatusState.java
src/main/java/hudson/plugins/tfs/model/Link.java
src/main/java/hudson/plugins/tfs/model/PullRequestMergeCommitCreatedEventArgs.java
src/main/java/hudson/plugins/tfs/model/URIMorpher.java
src/main/java/hudson/plugins/tfs/model/VstsGitStatus.java
src/main/java/hudson/plugins/tfs/model/WorkItem.java
src/test/java/hudson/plugins/tfs/model/GitCodePushedEventArgsTest.java
src/test/java/hudson/plugins/tfs/model/GitStatusContextTest.java
src/test/java/hudson/plugins/tfs/model/PullRequestMergeCommitCreatedEventArgsTest.java
src/test/java/hudson/plugins/tfs/model/VstsGitStatusTest.java

Some upcoming features will need these simple data structures, serialized to and/or from JSON.  The data structures are presented in isolation to simplify the code review.

Add some data structures for future use

---

src/main/java/hudson/plugins/tfs/VstsCollectionConfiguration.java
src/main/java/hudson/plugins/tfs/model/HttpMethod.java
src/main/java/hudson/plugins/tfs/util/UriHelper.java
src/main/java/hudson/plugins/tfs/util/VstsRestClient.java
src/test/java/hudson/plugins/tfs/util/UriHelperTest.java
src/test/java/hudson/plugins/tfs/util/VstsRestClientTest.java

In preparation for a fair amount of interactions with VSTS, created the `VstsRestClient` class as a façade.  A sample of its use can be found in `VstsCollectionConfiguration`, for testing the collection URL paired with the credentials.
Manual testing
--------------
1. Temporarily re-enabled the `ping()` test and ran it with the necessary parameters to connect to a VSTS account.  The ping succeeded.
2. Launched a test Jenkins instance and navigated to the global configuration.  For a VSTS collection URL, clicked the [Test connection] button for:
1. Valid credentials: **Success!**
2. Invalid credentials: **Error: Server returned HTTP response code: 401 for URL: https://{collectionUrl}/_apis/connectiondata**
3. No credentials: **Error: VSTS accounts need credentials, preferably a Personal …

Introduce a simple VSTS REST client

---

pom.xml
src/main/java/hudson/plugins/tfs/VstsCollectionConfiguration.java
src/main/java/hudson/plugins/tfs/VstsHookEventName.java
src/main/java/hudson/plugins/tfs/VstsWebHook.java
src/main/java/hudson/plugins/tfs/model/HttpMethod.java
src/main/java/hudson/plugins/tfs/util/MediaType.java
src/main/java/hudson/plugins/tfs/util/StringBodyParameter.java
src/main/java/hudson/plugins/tfs/util/StringHelper.java
src/main/java/hudson/plugins/tfs/util/VstsRestClient.java
src/test/java/hudson/plugins/tfs/util/StringHelperTest.java

These changes add a framework for a VSTS endpoint, with the events we expect to be able to receive from Visual Studio Team Services and Team Foundation Server.
The `VstsWebHook` exposes the `/vsts-hook/` URL where payloads may be POSTed with an event name.
Manual testing
--------------
1. Run `mvn hpi:hpl` to prepare the `tfs.hpl` file, then fix it up to add the TFS SDK JAR to the `CLASSPATH`.  This will allow us to test our plugin in a local Jenkins instance without having to re-deploy.
2. Launch the local Jenkins instance on port 9090: `java -jar jenkins.war --httpPort=9090`
1. You can see it is responding at `http://localhost:9090`
3. Use cURL to POST to the new `/vsts-hook/` endpoint in `PING` mode, sourcing the body of the request from the `git_code_pushed.json` text file: `curl …

Add base for VSTS web hook

---

src/main/java/hudson/plugins/tfs/CommitParameterAction.java
src/main/java/hudson/plugins/tfs/VstsHookEventName.java
src/main/java/hudson/plugins/tfs/VstsPushCause.java
src/main/java/hudson/plugins/tfs/VstsPushTrigger.java
src/main/java/hudson/plugins/tfs/VstsWebHook.java
src/main/java/hudson/plugins/tfs/model/GitCodePushedEventArgs.java
src/main/resources/hudson/plugins/tfs/VstsPushTrigger/VstsPollingAction/index.jelly
src/main/resources/hudson/plugins/tfs/VstsPushTrigger/help.html
src/test/java/hudson/plugins/tfs/CommitParameterActionTest.java
src/test/java/hudson/plugins/tfs/VstsHookEventNameTest.java

These changes add a **Build when a change is pushed to VSTS** *Build Trigger*, pictured below:
...which has been activated through the `/vsts-hook/` using the `GIT_CODE_PUSHED` event.
Manual testing
--------------
Some steps below will use cURL to POST to the `/vsts-hook/` endpoint in `GIT_CODE_PUSHED` mode, sourcing the body of the request from the `git_code_pushed.json` text file: `curl --request POST http://localhost:9090/vsts-hook/?event=GIT_CODE_PUSHED --header 'Content-Type: application/json; charset=utf-8' --upload-file git_code_pushed.json`
The `git_code_pushed.json` file contains the following JSON:
```json
{
"collectionUri":"https://mseng.visualstudio.com",
"repoUri":"https://mseng.visualstudio.com/Personal/_git/olivida.gcm4ml",
"projectId":"Personal",
"repoId":"olivida.gcm4ml", …
```

Add a VSTS push trigger

---

src/main/java/hudson/plugins/tfs/VstsCollectionConfiguration.java
src/main/java/hudson/plugins/tfs/VstsCompletedStatusPostBuildAction.java
src/main/java/hudson/plugins/tfs/VstsPendingStatusBuildStep.java
src/main/java/hudson/plugins/tfs/VstsPluginGlobalConfig.java
src/main/java/hudson/plugins/tfs/model/GitStatusState.java
src/main/java/hudson/plugins/tfs/model/GitStatusStateMorpher.java
src/main/java/hudson/plugins/tfs/model/VstsGitStatus.java
src/main/java/hudson/plugins/tfs/util/StringHelper.java
src/main/java/hudson/plugins/tfs/util/UriHelper.java
src/main/java/hudson/plugins/tfs/util/VstsRestClient.java
src/main/java/hudson/plugins/tfs/util/VstsStatus.java
src/test/java/hudson/plugins/tfs/model/VstsGitStatusTest.java
src/test/java/hudson/plugins/tfs/util/UriHelperTest.java

This pull request adds a **Set pending status for VSTS commit or pull request** _build step_ as well as a **Set completion status for VSTS commit or pull request** _post-build action_, as shown below in my test job:
Manual testing
--------------
1. Triggered the `/vsts-hook/` with a specific commit, which queued my test job.
2. As soon as the Maven build started, I went to check on the commit in VSTS.  It had indeed received the "Pending" status.
3. As soon as the build completed successfully, I went to check on the commit in VSTS.  It had indeed received a "Success" status and was linking back to the Jenkins job.
4. I repeated the test, this time arranging for the build to fail.  VSTS indeed reported a "Failure" status, also linking back to the Jenkins job.

Report pending and completion status to the associated VSTS commit

---

src/main/java/hudson/plugins/tfs/PullRequestParameterAction.java
src/main/java/hudson/plugins/tfs/VstsHookCause.java
src/main/java/hudson/plugins/tfs/VstsHookEventName.java
src/main/java/hudson/plugins/tfs/VstsPushTrigger.java
src/main/java/hudson/plugins/tfs/VstsWebHook.java
src/main/java/hudson/plugins/tfs/util/VstsRestClient.java
src/main/java/hudson/plugins/tfs/util/VstsStatus.java
src/test/java/hudson/plugins/tfs/VstsHookEventNameTest.java

This pull request augments the recently-added build step and post-build action to also handle pull request status, assuming the right payload was delivered to the web hook.
Manual testing
--------------
1. Configured a freestyle job to use the TFS plugin's recently-added **Set pending status** build step as well as the **Set completion status** post-build action: ![image](https://cloud.githubusercontent.com/assets/297515/17075149/c169d12c-5058-11e6-88dd-094f50fa6b65.png)
2. Triggered the `/vsts-hook/` as the PULL_REQUEST_MERGE_COMMIT_CREATED event with a specific commit, pull request ID and iteration ID, which queued my test job.
3. Because there's no UI for the pull request status, I visited the pull request iteration's `/statuses` URL in my web browser to confirm that the "Pending" and …

Report pending and completion status to the associated VSTS pull request

---

src/main/java/hudson/plugins/tfs/TeamPushTrigger.java
src/main/java/hudson/plugins/tfs/model/GitCodePushedHookEvent.java
src/main/java/hudson/plugins/tfs/model/PullRequestMergeCommitCreatedHookEvent.java

Upon review of the Jenkins integration specification, it was discovered that there's a need to be able to queue another Jenkins build related to a given pull request if a previous associated build was determined to have failed due to circumstances unrelated to the changes in the pull request, such as a race condition in an unrelated unit test.
Manual testing
--------------
1. Using curl, POST a `gitCodePushed` event and notice that the reply is "Scheduled polling <project>", with no build actually started (because there hasn't been anything new).
2. Using curl, POST a `pullRequestMergeCommitCreated ` event and notice that the reply is "Scheduled <project>", with a corresponding build started, hence bypassing polling.

Bypass polling when pullRequestMergeCommitCreated event is posted

---

src/main/java/hudson/plugins/tfs/commands/ListWorkspacesCommand.java
src/main/java/hudson/plugins/tfs/model/Workspaces.java
src/test/java/hudson/plugins/tfs/commands/ListWorkspacesCommandTest.java

The documentation for `VersionControlClient#queryWorkspaces(String, String, String, WorkspacePermissions)` says:
the computer name to match, null to match all. Use
LocalHost.getShortName() to match workspaces for this computer.
Manual testing
--------------
1. Deploy version 4.1.0 and create a job that uses TFVC, making sure it executes on an agent and not MASTER.  Queue a build and watch the list of workspaces include other computers than the selected Jenkins agent.
2. Deploy this branch as of 6df8e93 and queue the job again.  This time the list of workspaces includes only the selected Jenkins agent.
3. Deploy this branch as of 743198f4a2dc5b472ba5eeb246ea26bcc7da539a and queue the job one last time.  This time, no workspaces are listed!

JENKINS-30330: Only request workspaces for the current computer

---

src/main/java/hudson/plugins/tfs/model/PullRequestMergeCommitCreatedEventArgs.java
src/main/java/hudson/plugins/tfs/util/TeamRestClient.java
src/main/java/hudson/plugins/tfs/util/TeamStatus.java

It turns out we don't always know which pull request iteration a build might be requested for, so added a method for that REST endpoint and now calling it accordingly.
Manual testing
--------------
1. Using curl, POST a `pullRequestMergeCommitCreated` event as before and notice that the corresponding pull request iteration status is still reported as before this change.
2. Temporarily remove `iterationId` from the payload, repeat the above test and notice that the corresponding pull request status (without an iterationId) is now reported.

Support non-specific pull request status

---

src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
src/main/java/hudson/plugins/tfs/model/AbstractCommand.java
src/main/java/hudson/plugins/tfs/model/BuildCommand.java
src/main/java/hudson/plugins/tfs/model/BuildWithParametersCommand.java
src/main/java/hudson/plugins/tfs/model/PingCommand.java
src/main/resources/hudson/plugins/tfs/model/BuildCommand.json
src/main/resources/hudson/plugins/tfs/model/BuildWithParametersCommand.json

The `/team-build/` endpoint now supports `/team-build/buildWithParameters/JOB_NAME` in both structured form and legacy form modes.
Manual testing
--------------
1. Given the following `buildWithParameters.json` file:
```json
{
"parameter":
[
{"name": "id", "value": "123"},
{"name": "verbosity", "value": "high"}
],
"team-parameters":
{
"collectionUri":"https://mseng.visualstudio.com",
"repoUri":"https://mseng.visualstudio.com/Personal/_git/olivida.gcm4ml",
"projectId":"Personal",
"repoId":"olivida.gcm4ml",
"commit":"8a76fbe5c9e087491d672c7951bf2613be35de44",
"pushedBy":"olivida"
}
}
```
...run the following command to test the structured form mode: `curl --request PUT http://localhost:9090/team-build/build/param --data-urlencode json@buildWithParameters.json --user …

Add the ability to build with parameters

---

src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java

This adds support for the "Trigger builds remotely (e.g., from scripts)" trigger (which has an authentication token), as well as POST with crumbs, when CSRF protection is enabled.
Manual testing
--------------
1. Enabled "Prevent Cross Site Request Forgery exploits" in the Global Security.
2. Using `curl`, fetched the crumb for a user, then inserted it as a header when I POSTed to the `/team-build/build/` endpoint for a job.  A build was queued.
3. Created a job that used the "Trigger builds remotely (e.g., from scripts)" trigger, then used `curl` to PUT to the `/team-build/build/` endpoint for it, providing the `token` as a form body parameter.  A build was queued.

Make permission check behave exactly like Jenkins'

---

src/main/java/hudson/plugins/tfs/commands/GetFilesToWorkFolderCommand.java
src/test/java/hudson/plugins/tfs/commands/GetFilesToWorkFolderCommandTest.java

Use the same approach as in the list workspaces command.
- wrapped flag around logging
- set flag to false by default
- added comment to add property at later stage if desired
- updated unit test
Also added count of resources downloaded and added that to the log.
Verified in dev instance of Jenkins with numerous validations jobs. Also should pass cloudbees build.

Deactivate logging of each resource get in build log

---

src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
src/main/java/hudson/plugins/tfs/model/BuildCommand.java

It turns out the Jenkins Queue Build task will use structured form submission and we decided on adding a `team-build` section to the `json` parameter.
Manual testing
--------------
1. Craft the following `buildWithTeamBuild.json` file:
```json
{
"parameter":
[
{"name": "id", "value": "123"},
{"name": "verbosity", "value": "high"}
],
"team-build":
{
"Build.Repository.Provider": "TfGit",
"System.TeamFoundationCollectionUri": "https://mseng.visualstudio.com",
"Build.Repository.Uri": "https://mseng.visualstudio.com/Personal/_git/olivida.gcm4ml",
"System.TeamProject": "Personal",
"Build.Repository.Name": "olivida.gcm4ml",
"Build.SourceVersion": "8a76fbe5c9e087491d672c7951bf2613be35de44",
"Build.RequestedFor": "olivida"
}
}
```
2. Use `curl` to trigger a build of the `param` parameterized job: …

Add support for "team-build" section in structured form for /team-build/build

---

src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
src/main/java/hudson/plugins/tfs/model/BuildCommand.java
src/main/java/hudson/plugins/tfs/model/GitPullRequestMergedEvent.java
src/main/java/hudson/plugins/tfs/model/GitPushEvent.java
src/main/resources/hudson/plugins/tfs/model/GitPullRequestMergedEvent.json
src/main/resources/hudson/plugins/tfs/model/GitPushEvent.json
src/test/java/hudson/plugins/tfs/model/GitPullRequestMergedEventTest.java
src/test/java/hudson/plugins/tfs/model/GitPushEventTest.java

To simplify the event processing on the Team Services end, accept the Team Services event payloads as provided and map them to the corresponding *EventArgs classes.
Manual testing
--------------
1. Crafted the following `gitPush.json` file, which simulates a subset of the `git.push` payload one may get from Team Services:
```json
{
"eventType": "git.push",
"resource": {
"commits": [
{
"commitId": "6a23fc7afec31f0a14bade6544bed4f16492e6d2"
}
],
"repository": {
"name": "olivida.gcm4ml",
"url": "https://mseng.visualstudio.com/_apis/git/repositories/278d5cd2-584d-4b63-824a-2ba458937249",
"project": {
"name": "Personal"
},
"remoteUrl": "https://mseng.visualstudio.com/Personal/_git/olivida.gcm4ml"
},
"pushedBy": {
"displayName": "olivida"
}
}
}
```
2. Ran `curl` as follows to hit the new …

Add gitPush and gitPullRequestMerged events that accept Team Services payloads

---

src/main/java/hudson/plugins/tfs/model/BuildCommand.java

Manual testing
--------------
1. Ran `curl --request POST http://localhost:9090/team-build/build/param --data-urlencode json@buildWithTeamBuild.json` with a payload containing a `team-build` section that had:
1. `"Build.Repository.Provider": "TfGit",` => success!
2. `"Build.Repository.Provider": "TfsGit",` => success!

Support both TfGit and TfsGit providers

---

src/main/java/hudson/plugins/tfs/TeamCollectionConfiguration.java
src/main/java/hudson/plugins/tfs/TeamCompletedStatusPostBuildAction.java
src/main/java/hudson/plugins/tfs/TeamPendingStatusBuildStep.java

Without the changes in this branch, if the **Set build pending status in TFS/Team Services** build step or the **Set build completion status in TFS/Team Services** post-build action were added _without_ adding the corresponding Team Project Collection URL in the global configuration, the build output would contain:
ERROR: Error while trying to update pending status in TFS/Team Services
net.sf.json.JSONException: A JSONObject text must begin with '{' at character 1 of <!DOCTYPE(...)>
(...)
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>
Visual Studio Team Services | Sign In
(...lots of HTML...)
</html>
at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:499)
at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:919)
at …

Detect missing team project collection configuration

---

src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmIntegrationTest.java
src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java
src/test/java/hudson/plugins/tfs/browsers/TeamSystemWebAccessBrowserTest.java

This branch consists only of refactors and conversions designed to simplify the addition of fields representing new settings to the `TeamFoundationServerScm` class.
Instead of adding parameters to the constructor(s) and propagating to all the tests, adding a setter annotated with `@DataBoundSetter` works just as well and is much less disruptive.  The approach is also clearly documented.
Manual testing
--------------
1. I edited a job that used the TFVC SCM and confirmed that the settings were still being saved in the job's `config.xml` file and that nothing broke as a result of these changes.
1. I tested adding and removing values to the `cloakedPaths` field and queuing the job.
2. I experimented with turning on and off `userUpdate` and then queuing the job.
3. The lack of catastrophy …

Improve construction of TeamFoundationServerScm

---

src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
src/main/java/hudson/plugins/tfs/model/AbstractCommand.java
src/main/java/hudson/plugins/tfs/model/AbstractHookEvent.java
src/main/java/hudson/plugins/tfs/model/BuildCommand.java
src/main/java/hudson/plugins/tfs/model/BuildParameter.java
src/main/java/hudson/plugins/tfs/model/GitPullRequestMergedEvent.java
src/main/java/hudson/plugins/tfs/model/GitPushEvent.java
src/main/java/hudson/plugins/tfs/model/PingCommand.java
src/main/java/hudson/plugins/tfs/model/PingHookEvent.java
src/main/java/hudson/plugins/tfs/model/TeamBuildPayload.java
src/main/java/hudson/plugins/tfs/model/servicehooks/Event.java
src/main/java/hudson/plugins/tfs/model/servicehooks/EventScope.java
src/main/java/hudson/plugins/tfs/model/servicehooks/FormattedEventMessage.java
src/main/java/hudson/plugins/tfs/model/servicehooks/ResourceContainer.java
src/main/java/hudson/plugins/tfs/util/ResourceHelper.java
src/test/java/hudson/plugins/tfs/TeamEventsEndpointTest.java
src/test/java/hudson/plugins/tfs/model/GitPullRequestMergedEventTest.java
src/test/java/hudson/plugins/tfs/model/GitPushEventTest.java
src/test/resources/hudson/plugins/tfs/git.push-sample.json

This branch is mostly about eliminating technical debt around the determination of collection URI and improving the robustness of the endpoints.  A lot of the decoding is now done more automatically by Jackson deserialization, leading to stronger typing and less chance of error.  This also made it possible to remove some duplicated code that ended up no longer being used.
Manual testing
--------------
1. Crafted an event payload with an **eventType** of `git.pullrequest.merged` such that it contained a value for the upcoming `resourceContainers/collection/baseUrl`, then used `curl` to POST it to the `/team-events/gitPullRequestMerged` endpoint.
1. A breakpoint I had in the `GitPushEvent#determineCollectionUri()` method allowed me to verify that the `baseUrl` value would be used if it was …

Use collection URI in payloads, if possible

---

src/main/java/hudson/plugins/tfs/TeamCollectionConfiguration.java
src/main/java/hudson/plugins/tfs/TeamPushTrigger.java
src/main/java/hudson/plugins/tfs/model/AbstractHookEvent.java
src/main/java/hudson/plugins/tfs/util/TeamRestClient.java
src/main/java/hudson/plugins/tfs/util/TeamStatus.java
src/main/java/hudson/plugins/tfs/util/UriHelper.java
src/test/java/hudson/plugins/tfs/IntegrationTestHelper.java
src/test/java/hudson/plugins/tfs/TeamCollectionConfigurationTest.java
src/test/java/hudson/plugins/tfs/model/AbstractHookEventTest.java
src/test/java/hudson/plugins/tfs/util/UriHelperTest.java

TFS eventually acquired the concept of Team Project Collections to allow isolation between groups/projects (on the same server) and Visual Studio Team Services initially inherited this functionality by requiring `/DefaultCollection` in the URL.  After a while, Team Services removed the requirement of specifying `/DefaultCollection` in the URL while still supporting URLs with it.  This lead to a situation where the plugin would consider two functionally-identical URLs as different collections.
This pull request aims to mitigate the confusion by:
1. Enforcing the lack of a path in Team Services collection URLs in the global configuration.
2. Emitting warnings when jobs _almost match_ a given event URL.
3. Emitting warnings when no jobs exactly matched a given event URL.
Manual testing …

Reduce the chance of error with Team Services URLs

---

src/main/java/hudson/plugins/tfs/TeamBuildDetailsAction.java
src/main/java/hudson/plugins/tfs/TeamCompletedStatusPostBuildAction.java
src/main/java/hudson/plugins/tfs/TeamPendingStatusBuildStep.java
src/main/java/hudson/plugins/tfs/UnsupportedIntegrationAction.java
src/main/java/hudson/plugins/tfs/model/BuildCommand.java
src/main/java/hudson/plugins/tfs/util/TeamStatus.java
src/main/resources/hudson/plugins/tfs/TeamBuildDetailsAction/summary.jelly

This pull request makes it so that a POST to `/team-build/build` with a payload that contains a `team-build` section will now contribute the `TeamBuildDetailsAction` to the build.  This new action manifests itself as (see the screenshot following for an example):
1. An (unlinked) entry on the left-hand side of the build labelled **TFS/Team Services build**.
2. An addition to the build summary, where we can read **Triggered by TFS/Team Services build ${Build.BuildNumber} of '${Build.BuildDefinitionName}'**, hyperlinked to the build in TFS/Team Services.
Since this was originally posted, a discrepancy was noticed between the integration specification and the implementation, plus an improvement was made in the user experience.
For the latter, commits 9c2599ef2cefcf7d9ae743fe8d8d862f66972fb6 …

Link back to the TFS/Team Services build that triggered the Jenkins build

---

src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
src/main/java/hudson/plugins/tfs/TeamPullRequestMergedDetailsAction.java
src/main/java/hudson/plugins/tfs/TeamPushTrigger.java
src/main/java/hudson/plugins/tfs/model/AbstractHookEvent.java
src/main/java/hudson/plugins/tfs/model/BuildCommand.java
src/main/java/hudson/plugins/tfs/model/GitPullRequestEx.java
src/main/java/hudson/plugins/tfs/model/GitPullRequestMergedEvent.java
src/main/java/hudson/plugins/tfs/model/GitPushEvent.java
src/main/java/hudson/plugins/tfs/model/PingHookEvent.java
src/main/java/hudson/plugins/tfs/util/ActionHelper.java
src/main/resources/hudson/plugins/tfs/TeamPullRequestMergedDetailsAction/index.jelly
src/main/resources/hudson/plugins/tfs/TeamPullRequestMergedDetailsAction/summary.jelly
src/test/java/hudson/plugins/tfs/TeamEventsEndpointTest.java

This pull request enhances both the `/team-events/` and `/team-build/` endpoints to contribute the new `TeamPullRequestMergedDetailsAction`, which manifests itself as:
1. A **TFS/Team Services pull request** link in the side-panel:
2. A section in the build summary page that displays a link to the pull request, its title & author and, if any were provided, links to associated work items:
3. A **TFS/Team Services pull request** page, linked from # 1 above, with a few more details and links:
4. Some metadata in a build's `build.xml` file, from which # 2 and # 3 above are possible.
Manual testing
--------------
1. Using `curl`, crafted a payload for the `/team-events/pullRequestMerged` endpoint and posted it.  A build of the "Git" job was queued and the results are seen in screenshot # 2 …

Display "pull request merged" event details in build summary & details

---

README.md
src/main/java/hudson/plugins/tfs/TeamPluginGlobalConfig.java
src/main/java/hudson/plugins/tfs/commands/AbstractCallableCommand.java
src/main/java/hudson/plugins/tfs/commands/ServerConfigurationProvider.java
src/main/java/hudson/plugins/tfs/model/ClonePersistenceStoreProvider.java
src/main/java/hudson/plugins/tfs/model/ExtraSettings.java
src/main/java/hudson/plugins/tfs/model/ModernConnectionAdvisor.java
src/main/java/hudson/plugins/tfs/model/Server.java
src/main/resources/hudson/plugins/tfs/TeamPluginGlobalConfig/config.groovy
src/main/resources/hudson/plugins/tfs/TeamPluginGlobalConfig/help-configFolderPerNode.html
src/test/java/hudson/plugins/tfs/EndToEndTfs.java
src/test/java/hudson/plugins/tfs/commands/AbstractCallableCommandTest.java
src/test/java/hudson/plugins/tfs/model/ProjectTest.java
src/test/java/hudson/plugins/tfs/model/ServerTest.java

In some environments, the "home" directory is mounted over a network and shared between many computers, including Jenkins servers and their associated build nodes, which eventually leads to corruption of the configuration directory used for TFVC workspaces.  This branch introduces a new, advanced setting that uses a sub-directory for each computer, copying the current configuration directory (if one is found) on the next run.
In other words, turning on the new **Store TFVC configuration in computer-specific folders** option means the TFS SDK will use the following base path for its <code>Cache</code>, <code>Configuration</code> and <code>Logs</code> directories:
`~/.microsoft/Team Foundation/4.0/${HOSTNAME}/`
Manual testing
--------------
1. **Jenkins** > **Manage Jenkins** > **Configure …

Add support for per-computer TFVC configuration folders

---

src/main/java/hudson/plugins/tfs/actions/CheckoutAction.java
src/main/java/hudson/plugins/tfs/commands/AbstractCallableCommand.java
src/main/java/hudson/plugins/tfs/commands/GetWorkspaceMappingCommand.java
src/main/java/hudson/plugins/tfs/commands/IsWorkspaceMappedCommand.java
src/main/java/hudson/plugins/tfs/commands/NewWorkspaceCommand.java
src/main/java/hudson/plugins/tfs/model/MockableVersionControlClient.java
src/main/java/hudson/plugins/tfs/model/Workspaces.java
src/test/java/hudson/plugins/tfs/actions/CheckoutActionTest.java
src/test/java/hudson/plugins/tfs/commands/NewWorkspaceCommandTest.java

A number of defects related to workspace mappings were fixed and the builds can now withstand all sorts of things that used to break the build, such as:
1. Corrupted configuration
2. Unmapped folder
3. Deleted workspace
4. Renamed workspace
5. Outdated configuration cache

Withstand all sorts of workspace-related mishaps

---

README.md
src/main/java/hudson/plugins/tfs/model/ModernConnectionAdvisor.java
src/main/java/hudson/plugins/tfs/model/ModernHTTPClientFactory.java
src/main/java/hudson/plugins/tfs/model/ProxyHostEx.java
src/main/java/hudson/plugins/tfs/model/Server.java
src/main/java/hudson/plugins/tfs/model/WebProxySettings.java
src/main/java/hudson/plugins/tfs/util/TeamRestClient.java

This pull request passes along the `User name` and `Password` values, if supplied, from the Jenkins **HTTP Proxy Configuration** to the HTTP client factory used by the TFS SDK for Java.
This pull request also adds proxy support (authenticated or otherwise) to the `TeamRestClient`, which is used for further integration with TFS/Team Services.
Manual testing
--------------
1. Installed Squid and enabled authentication.
2. Configured Jenkins to use the Squid instance, minus the credentials.
1. The `Validate Proxy` button correctly showed a result of HTTP 407.
2. Queued a TFVC-based build against a repo hosted in Team Services.
1. Confirmed that it was attempting to use the proxy server and failing with HTTP 407.
3. Triggered Team Services Git-based build via the `/team-build/` endpoint for a …

Improve support for proxy servers (including those that need authentication)

---

tfs/src/main/java/hudson/plugins/tfs/TeamCompletedStatusPostBuildAction.java
tfs/src/main/java/hudson/plugins/tfs/TeamPendingStatusBuildStep.java
tfs/src/main/java/hudson/plugins/tfs/UnsupportedIntegrationAction.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamStatus.java

Manual testing
--------------
1. Configured a job with the **Set build pending status in TFS/Team Services** build step and the **Set build completion status in TFS/Team Services** post-build action.
2. Triggered a build via the `/team-build/` endpoint with a payload containing a `team-build` section (just like the Jenkins Queue Job task would do).
1. The _Console Output_ contained: `NOTICE: You selected 'Set build pending status in TFS/Team Services' on your Jenkins job, but this option has no effect when calling the job from the 'Jenkins Queue Job' task in TFS/Team Services.` as well as `NOTICE: You selected 'Set build completion status in TFS/Team Services' on your Jenkins job, but this option has no effect when calling the job from the 'Jenkins Queue Job' task in TFS/Team Services.` …

Converted ERROR into NOTICE & improved wording

---

tfs/pom.xml
tfs/src/main/java/hudson/plugins/tfs/model/ModernHTTPClientFactory.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamRestClient.java

Note
----
I've implemented the User-Agent string using the TFS SDK's extension (`ConfigurableHTTPClientFactory#getUserAgentExtraString()`), which means we get 30 characters to append to what it generates and it's really tight with the current string: `5.1.1-SNAPSHOT` gets truncated to `5.1.1-S`.  We should still have enough room for 2 2-digit groups, such as `5.10.11`, but then it will be difficult to distinguish an official release from a SNAPSHOT build.  We could give ourselves a bit more breathing room if we shrunk the `TFS Plugin for Jenkins ` prefix and I'm open to suggestions.
Manual testing
==============
1. Launched Jenkins with the plugin in "development testing" mode (using the `.hpl` file), set a breakpoint in the `TeamRestClient` and clicked the [Test connection] button.
1. …

Set the User-Agent header with plugin version

---

tfs/src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/TeamCollectionConfiguration.java
tfs/src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/ExtraSettings.java
tfs/src/main/java/hudson/plugins/tfs/model/HttpMethod.java
tfs/src/main/java/hudson/plugins/tfs/model/ListOfGitRepositories.java
tfs/src/main/java/hudson/plugins/tfs/model/Server.java
tfs/src/main/java/hudson/plugins/tfs/util/EndpointHelper.java
tfs/src/main/java/hudson/plugins/tfs/util/MediaType.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamRestClient.java

Details
-------
1. Some users reported that the [Test connection] button would give the same results regardless of the selected _Credentials_.  This is due to the `HttpURLConnection` attempting NTLM authentication on Windows, even if that's not what was requested.  The `TeamRestClient` was rewritten to use the Apache HttpClient instead.
2. The [Test connection] button didn't perform a very good test, so it was improved to attempt to connect with the SOAP API and then fallback to the REST API with a call that validates the code_read permission.
Manual testing
==============
All the following tests were performed on a Jenkins server running on Windows.
Team Services
-------------
1. Provided incorrect credentials for a Team Services account and clicked [Test connection]
1. The result was …

Fix TeamRestClient for TFS on Windows and improve "Test connection" button

---

README.md
tfs/src/main/java/hudson/plugins/tfs/TeamCompletedStatusPostBuildAction.java
tfs/src/main/java/hudson/plugins/tfs/TeamGlobalStatusAction.java
tfs/src/main/java/hudson/plugins/tfs/TeamGlobalStatusPoster.java
tfs/src/main/java/hudson/plugins/tfs/TeamPendingStatusBuildStep.java
tfs/src/main/java/hudson/plugins/tfs/TeamPluginGlobalConfig.java
tfs/src/main/java/hudson/plugins/tfs/TeamPushTrigger.java
tfs/src/main/java/hudson/plugins/tfs/model/AbstractHookEvent.java
tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java
tfs/src/main/resources/hudson/plugins/tfs/TeamPluginGlobalConfig/config.groovy
tfs/src/main/resources/hudson/plugins/tfs/TeamPluginGlobalConfig/help-enableTeamPushTriggerForAllJobs.html
tfs/src/main/resources/hudson/plugins/tfs/TeamPluginGlobalConfig/help-enableTeamStatusForAllJobs.html

This pull request adds two "global options" to Jenkins, pictured below:
1. **Enable Push Trigger for all jobs**
2. **Enable Team Status for all jobs**
Manual testing
==============
1. Enable both new options and configure a few jobs with special cases:
1. One job to opt-out of the global push trigger.
2. One job with the "Build when a change is pushed to TFS/Team Services" trigger enabled.
3. One job with the "Set build pending status in TFS/Team Services" build step.
4. One job with the "Set build completion status in TFS/Team Services" post-build action.
5. One job with both the "Set build pending status in TFS/Team Services" build step and the "Set build completion status in TFS/Team Services" post-build action.
2. Hit the `/team-events/gitPullRequestMerged` endpoint with a payload …

Automatic integration

---

tfs/src/main/java/hudson/plugins/tfs/TeamPluginGlobalConfig.java
tfs/src/main/java/hudson/plugins/tfs/model/AliasOnlyUserAccountMapper.java
tfs/src/main/java/hudson/plugins/tfs/model/DomainUserAccountMapper.java
tfs/src/main/java/hudson/plugins/tfs/model/Project.java
tfs/src/main/java/hudson/plugins/tfs/model/TfsUserLookup.java
tfs/src/main/java/hudson/plugins/tfs/model/UserAccountMapper.java
tfs/src/main/java/hudson/plugins/tfs/model/UserAccountMapperDescriptor.java
tfs/src/main/resources/hudson/plugins/tfs/TeamPluginGlobalConfig/config.groovy
tfs/src/main/resources/hudson/plugins/tfs/TeamPluginGlobalConfig/help-userAccountMapper.html
tfs/src/main/resources/hudson/plugins/tfs/model/AliasOnlyUserAccountMapper/config.groovy
tfs/src/main/resources/hudson/plugins/tfs/model/DomainUserAccountMapper/config.groovy

Hi @olivierdagenais , these are my testing results.
I ran the build through Maven and made sure that the jar and hpi files were successfully created.
Once the hpi file was created, I uploaded the file and installed it on our company's Test Jenkins.
The plugin worked as expected and the UI interface made it easy for us to chose whether to keep the User ID with the domain name or User ID without the domain name. 
Example: DomainName/User ID to Only User ID

User account mapping

---

tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java

This addresses issue JENKINS-40283 that addresses a crash with the following stack trace:
```
java.lang.Error: java.net.URISyntaxException: Cannot parse Git URI-ish: The uri was empty or null
at hudson.plugins.tfs.model.GitCodePushedEventArgs.getRepoURIish(GitCodePushedEventArgs.java:23)
at hudson.plugins.tfs.CommitParameterAction.&lt;init>(CommitParameterAction.java:20)
at hudson.plugins.tfs.model.BuildCommand.contributeTeamBuildParameterActions(BuildCommand.java:227)
at hudson.plugins.tfs.model.BuildCommand.perform(BuildCommand.java:110)
```
**Tested as follows:**
1. `mvn clean verify` - All tests pass
2. I verified failure with the above stack trace when the "Jenkins Queue Job" task invoked a Jenkins job from TFS Release Management.  Then, I applied this code change and verified that …

Fix exception when invoked from TFS Release Management (JENKINS-40283)

---

tfs/src/main/java/hudson/plugins/tfs/model/servicehooks/EventScope.java
tfs/src/main/resources/hudson/plugins/tfs/model/GitPullRequestMergedEvent.json
tfs/src/main/resources/hudson/plugins/tfs/model/GitPushEvent.json
tfs/src/test/java/hudson/plugins/tfs/model/servicehooks/EventScopeTest.java
tfs/src/test/resources/hudson/plugins/tfs/git.push-sample.json

The new unit test reproduces [JENKINS-40155](https://issues.jenkins-ci.org/browse/JENKINS-40155) and the additions to `EventScope` fix it.  I also sprinkled `"scope": "all",` in JSON files used as examples and for tests, just to be sure. :smirk:

JENKINS-40155: Fix event's scope deserialization

---

tfs/src/main/java/hudson/plugins/tfs/model/AbstractHookEvent.java
tfs/src/main/java/hudson/plugins/tfs/model/GitPushEvent.java
tfs/src/test/java/hudson/plugins/tfs/model/GitPushEventTest.java

```
Dez 01, 2016 1:47:22 PM SCHWERWIEGEND hudson.plugins.tfs.TeamEventsEndpoint dispatch
Error while performing reaction to 'gitPush' event.
java.lang.NullPointerException
  at hudson.plugins.tfs.model.GitPushEvent.determineCommit(GitPushEvent.java:100)
  at hudson.plugins.tfs.model.GitPushEvent.decodeGitPush(GitPushEvent.java:120)
  at hudson.plugins.tfs.model.GitPushEvent.perform(GitPushEvent.java:44)
  at hudson.plugins.tfs.TeamEventsEndpoint.innerDispatch(TeamEventsEndpoint.java:163)
  at hudson.plugins.tfs.TeamEventsEndpoint.dispatch(TeamEventsEndpoint.java:133)
  at hudson.plugins.tfs.TeamEventsEndpoint.doGitPush(TeamEventsEndpoint.java:201) 
```

getCommits can return null

---

tfs/src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/model/AbstractCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/PingCommand.java

Today when triggering a Pipeline job, we will get a "Project not found" exception as `WorkflowJob` is not of `AbstractProject` type.  
All information the plugin requires can be retrieved by `BuildableItem` and `ParameterizedJobMixin.ParameterizedJob` interface, and `WorkflowJob` implements both interfaces.  The change is to explicitly cast both `AbstractProject` and `WorkflowJob` down to `BuildableItem` and `ParameterizedJobMixin.ParameterizedJob` and pass it around as such.

Support WorkflowJob (Pipeline) jobs

---

tfs/src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java

In v5.3.3, we are assuming the jobname for a Multibranch Pipeline job is passed from VSTS / TFS JenkinsQueueJob task in the format of _${MultibranchPipelineJob}/${Branch}_.  This won't work for Multibranch Pipeline jobs in folders as we can't pinpoint which `/` splits the job and the branch.  
In JenkinsQueueJob task 1.115.0, we are adding a separate field to specify the branch name.  This will resolve all the ambiguities.   
This fix requires JenkinsQueueJob 1.115.0.

Allow VSTS JenkinsQueueJob to pass the branch name for multibranch pipeline job

---

.gitignore

Eclipse/M2e maintains files in each module folder and since we have a multi-module project now we need to expand the exclusion to any folder...

ignoring eclipse files also in the modules

---

tfs/src/main/java/hudson/plugins/tfs/model/Server.java

if isConfigFolderPerNode enabled, every checkout create a new ClonePersistenceStoreProvider instance in
Workstation.currentWorkstation HashMap and never be deleted

fix memory leak: Workstation.currentWorkstation

---

pom.xml
tfs/pom.xml
tfs/src/main/java/hudson/plugins/tfs/commands/AbstractCallableCommand.java
tfs/src/main/java/hudson/plugins/tfs/commands/DeleteWorkspaceCommand.java
tfs/src/main/java/hudson/plugins/tfs/commands/GetFilesToWorkFolderCommand.java
tfs/src/main/java/hudson/plugins/tfs/commands/GetWorkspaceMappingCommand.java
tfs/src/main/java/hudson/plugins/tfs/commands/LabelCommand.java
tfs/src/main/java/hudson/plugins/tfs/commands/ListWorkspacesCommand.java
tfs/src/main/java/hudson/plugins/tfs/commands/NewWorkspaceCommand.java
tfs/src/main/java/hudson/plugins/tfs/commands/RemoteChangesetVersionCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/Server.java
tfs/src/main/resources/hudson/plugins/tfs/TFSLabeler/config.jelly
tfs/src/main/resources/hudson/plugins/tfs/TFSLabeler/global.jelly
tfs/src/main/resources/hudson/plugins/tfs/TeamFoundationServerScm/config.jelly
tfs/src/main/resources/hudson/plugins/tfs/browsers/TeamSystemWebAccessBrowser/config.jelly
tfs/src/main/resources/hudson/plugins/tfs/model/ChangeLogSet/digest.jelly
tfs/src/main/resources/hudson/plugins/tfs/model/ChangeLogSet/index.jelly

[JENKINS-40806](https://issues.jenkins-ci.org/browse/JENKINS-40806)
- Increase parent POM version.
- Increase baseline.
- Include necessary dependencies.
- Include "escape-by-default" property in Jelly files.
- Use MasterToSlaveCallable needed in new baseline version.
@yacaovsnc @DavidStaheli @mosabua @reviewbybees

[JENKINS-40806] tfs plugin PCT issues against 2.19.4 and 2.32.1

---

tfs/src/test/java/hudson/plugins/tfs/FunctionalTest.java

The way we search for last build has changed in Jenkins 1.625.1, and our fakes doesn't work anymore.  Reaction work for #144.

faking the builds does not work anymore, fix tests related with it

---

tfs/src/main/java/hudson/plugins/tfs/TFSLabeler.java
tfs/src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/TeamCollectResultsPostBuildAction.java
tfs/src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/TeamUpdateWorkItemPostBuildAction.java
tfs/src/main/java/hudson/plugins/tfs/telemetry/TelemetryContextInitializer.java
tfs/src/main/java/hudson/plugins/tfs/telemetry/TelemetryHelper.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamStatus.java

This telemetry will be sent to Application Insights for tracking what features users are engaged with.

Adding basic telemetry to the plugin

---

pom.xml
tfs/src/main/java/hudson/plugins/tfs/ChangeSetReader.java
tfs/src/main/java/hudson/plugins/tfs/ChangeSetWriter.java
tfs/src/main/java/hudson/plugins/tfs/TFSLabeler.java
tfs/src/main/java/hudson/plugins/tfs/TeamBuildEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/TeamCollectResultsPostBuildAction.java
tfs/src/main/java/hudson/plugins/tfs/TeamCollectionConfiguration.java
tfs/src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
tfs/src/main/java/hudson/plugins/tfs/TeamPullRequestMergedDetailsAction.java
tfs/src/main/java/hudson/plugins/tfs/TeamPushCause.java
tfs/src/main/java/hudson/plugins/tfs/model/AbstractHookEvent.java
tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/BuildParameter.java
tfs/src/main/java/hudson/plugins/tfs/model/ChangeLogSet.java
tfs/src/main/java/hudson/plugins/tfs/model/ChangeSet.java
tfs/src/main/java/hudson/plugins/tfs/model/CredentialsConfigurer.java
tfs/src/main/java/hudson/plugins/tfs/model/GitCodePushedEventArgs.java
tfs/src/main/java/hudson/plugins/tfs/model/GitPullRequestEx.java
tfs/src/main/java/hudson/plugins/tfs/model/Link.java
tfs/src/main/java/hudson/plugins/tfs/model/ManualCredentialsConfigurer.java
tfs/src/main/java/hudson/plugins/tfs/model/NativeLibraryManager.java
tfs/src/main/java/hudson/plugins/tfs/model/Project.java
tfs/src/main/java/hudson/plugins/tfs/model/ProxyHostEx.java
tfs/src/main/java/hudson/plugins/tfs/model/Server.java
tfs/src/main/java/hudson/plugins/tfs/model/TeamBuildPayload.java
tfs/src/main/java/hudson/plugins/tfs/model/UserAccountMapper.java
tfs/src/main/java/hudson/plugins/tfs/util/BuildWorkspaceConfigurationRetriever.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamRestClient.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamStatus.java

[JENKINS-40807](https://issues.jenkins-ci.org/browse/JENKINS-40807)
After [JENKINS-40806](https://issues.jenkins-ci.org/browse/JENKINS-40806), Findbugs is run as part of the build. However, such builds does not fail if any error arise.
This change revert that behaviour and fixes/suppresses already present errors.
@reviewbybees @yacaovsnc

[JENKINS-40807] Fix Findbugs errors

---

tfs/src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
tfs/src/main/java/hudson/plugins/tfs/actions/CheckoutAction.java
tfs/src/main/java/hudson/plugins/tfs/commands/GetFilesToWorkFolderCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/Project.java
tfs/src/main/resources/hudson/plugins/tfs/TeamFoundationServerScm/config.jelly
tfs/src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java
tfs/src/test/java/hudson/plugins/tfs/actions/CheckoutActionTest.java
tfs/src/test/java/hudson/plugins/tfs/commands/GetFilesToWorkFolderCommandTest.java

To avoid problems when files are changed during the build.

Overwrite when getting files

---

tfs/pom.xml
tfs/src/main/java/hudson/plugins/tfs/JenkinsEventNotifier.java
tfs/src/main/java/hudson/plugins/tfs/TeamCollectionConfiguration.java
tfs/src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/listeners/JenkinsRunListener.java
tfs/src/main/java/hudson/plugins/tfs/model/ConnectHookEvent.java
tfs/src/main/java/hudson/plugins/tfs/model/ConnectionParameters.java
tfs/src/main/java/hudson/plugins/tfs/model/JobCompletionEventArgs.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamRestClient.java

Adding "team-events-connect" endpoint which allows TFS/VSTS to "connect" to the Jenkins server and start receiving events.

Adding JenkinsEventNotifier to send events back to TFS/VSTS

---

tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java

Updated the build command to check for any parameters that have not been defined and uses their default value.

Use default values for parameters when value not supplied

---

tfs/src/main/java/hudson/plugins/tfs/JenkinsEventNotifier.java

Add code to explicitly require either TLS 1.1 or 1.2. Also added a separate catch for the HttpHostConnectException to prevent it from being rethrown.

Prevent HttpConnectionError when getting JSON for Jenkins object

---

tfs/src/main/java/hudson/plugins/tfs/JenkinsEventNotifier.java

This is currently breaking the build

Adding the missing java.io.IOException import in JenkinsEventNotifier

---

tfs/src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java

The upgradeFromScrambledPassword() test was failing on Linux machines. Updating the test to only run on Windows OS.

Updating unit test to only run only windows OS

---

tfs/src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java

This test was previously updated to only run on windows, but it was really just an assert that was not working on other nodes running the tests.

Removing assert so test can run on all nodes

---

tfs/src/main/java/hudson/plugins/tfs/TeamFoundationServerScm.java
tfs/src/main/java/hudson/plugins/tfs/actions/CheckoutAction.java
tfs/src/main/java/hudson/plugins/tfs/commands/NewWorkspaceCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/Project.java
tfs/src/main/java/hudson/plugins/tfs/model/WorkspaceConfiguration.java
tfs/src/main/java/hudson/plugins/tfs/model/Workspaces.java
tfs/src/main/resources/hudson/plugins/tfs/TeamFoundationServerScm/config.jelly
tfs/src/main/resources/hudson/plugins/tfs/TeamFoundationServerScm/help-mappedPaths.html
tfs/src/test/java/hudson/plugins/tfs/TeamFoundationServerScmTest.java
tfs/src/test/java/hudson/plugins/tfs/actions/CheckoutActionTest.java
tfs/src/test/java/hudson/plugins/tfs/commands/NewWorkspaceCommandTest.java
tfs/src/test/java/hudson/plugins/tfs/model/ProjectTest.java
tfs/src/test/java/hudson/plugins/tfs/model/WorkspaceConfigurationTest.java
tfs/src/test/java/hudson/plugins/tfs/model/WorkspacesTest.java
tfs/src/test/java/hudson/plugins/tfs/util/BuildWorkspaceConfigurationRetrieverTest.java

This pull request adds the ability to cloak a folder and then explicitly map a sub folder, so that the cloaked folder will not be included in the checkout but the sub folder will be
This capability is useful in cases (like ours) where a TFS repository contains a large amount of code and each build only needs a 'small' amount of that code. For instance if the TFS repository looks like
$/
product-1
folder-1
folder-2
product-2
folder-1
folder-2
shared-1
folder-1
folder-1
folder-2
folder-2
folder-1
folder-2
shared-2
folder-1
folder-1
folder-2
folder-2
folder-1
folder-2
To build `product-1` the following folders are required
$/
product-1
folder-1
folder-2
shared-1
folder-1
folder-1
folder-2
shared-2
folder-1
To build `product-2` the following folders are required
$/
product-2
folder-1
folder-2 …

Allow users to map sub-folders of cloaked paths

---

pom.xml
tfs/pom.xml
tfs/src/main/java/hudson/plugins/tfs/TeamEventsEndpoint.java
tfs/src/main/java/hudson/plugins/tfs/telemetry/TelemetryContextInitializer.java

I was working on PCT for JEP-200, and finally I discovered that the plugin build does not work there. In this PR i tried to cleanup the POMs and code a bit.
@reviewbybees

Update POMs and cleanup the dependencies/code

---

tfs/src/main/java/hudson/plugins/tfs/JenkinsEventNotifier.java
tfs/src/main/java/hudson/plugins/tfs/listeners/JenkinsRunListener.java
tfs/src/main/java/hudson/plugins/tfs/model/AbstractHookEvent.java
tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java
tfs/src/main/java/hudson/plugins/tfs/model/TeamGitStatus.java
tfs/src/main/java/hudson/plugins/tfs/util/TeamStatus.java

Deduplicate code paths used for feeding back status to VSTS/TFS.
Further, set the "name" and "genre" fields to sane values:
VSTS uses these fiels for configuration of branch policies. Empty
strings are not permitted, thus this feature was broken on the part of
tfs-plugin.
Use the Jenkins root-URL as 'genre' and the job-name as 'name'.

Improve VSTS Service Hook integration

---

tfs/src/main/java/hudson/plugins/tfs/model/BuildCommand.java

There was a bug that caused a running job, triggered by a merge-commit Webhook,
being canceled regardless of what the running job's build cause was.
This fixes the misbehavior by just canceling builds that have the same
Pullrequest as a build cause.

BuildCommand: abort a build only if it was caused by the same PR

---

README.md
Releasing.md
Testing.md

Revised documents to refer to Azure DevOps instead of Visual Studio Team Services (VSTS)

Add Azure DevOps to repo docs

---

tfs/src/main/java/hudson/plugins/tfs/rm/ReleaseWebHookAction.java

The payload checksum was calculated after converting to UTF-8 string.
If we don't convert the payload as well, the checksum won't match.

Encoding payload string to UTF-8 before publishing the evennt.
